I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 319, in script
    if firstround:
  File "game/script.rpy", line 319, in <module>
    if firstround:
NameError: name 'firstround' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 319, in script
    if firstround:
  File "C:\Users\nateh\OneDrive\Pictures\RenPy\renpy-8.2.1-sdk\renpy\ast.py", line 1842, in execute
    if renpy.python.py_eval(condition):
  File "C:\Users\nateh\OneDrive\Pictures\RenPy\renpy-8.2.1-sdk\renpy\python.py", line 1209, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "C:\Users\nateh\OneDrive\Pictures\RenPy\renpy-8.2.1-sdk\renpy\python.py", line 1202, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 319, in <module>
    if firstround:
NameError: name 'firstround' is not defined

Windows-10-10.0.22621 AMD64
Ren'Py 8.2.1.24030407
Out-Of-Order-VN 1.0
Mon Apr  1 21:30:57 2024
